---

- name: Install docker-compose
  ansible.builtin.pip:
    name: docker-compose

- name: Update netbox directories
  ansible.builtin.file:
    path: "{{ base_dir }}/{{ item }}"
    state: directory
    recurse: true
  loop:
    - env

- name: Update environment files
  ansible.builtin.template:
    src: "env/{{ item }}.j2"
    dest: "{{ base_dir }}/env/{{ item }}"
    mode: "0644"
  loop:
    - netbox.env
    - postgres.env
    - redis-cache.env
    - redis.env
  notify: Restart netbox

- name: Update configuration files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ base_dir }}/{{ item }}"
    mode: "0644"
  loop:
    - docker-compose.yml
    - extra.py
  notify: Restart netbox

- name: Remove outdated files
  ansible.builtin.file:
    path: "{{ base_dir }}/{{ item }}"
    state: absent
  loop:
    - netbox.env
    - configuration/configuration.py
    - configuration/gunicorn_config.py

- name: Ensure services are running
  community.docker.docker_compose:
    project_src: "{{ base_dir }}"
    pull: True
  notify: Restart netbox
