---

- name: Get current netbox version
  docker_container:
    name: "{{ netbox_image }}"
    command: /bin/bash -c 'echo $VERSION'
  register: current_version
  changed_when: false

- name: Check for netbox updates
  docker_image_info:
    name: "{{ netbox_image }}"
  register: image_info
  changed_when: false

- name: Pull latest netbox image if available
  community.docker.docker_compose:
    project_src: "{{ netbox_base_dir }}"
    pull: yes
  when: image_info.exists and image_info.tag != current_version.stdout.strip()


- name: Update netbox directories
  ansible.builtin.file:
    path: "{{ netbox_base_dir }}/{{ item }}"
    state: directory
    recurse: true
  loop:
    - env

- name: Update environment files
  ansible.builtin.template:
    src: "env/{{ item }}.j2"
    dest: "{{ netbox_base_dir }}/env/{{ item }}"
    mode: "0644"
  loop:
    - netbox.env
    - postgres.env
    - redis-cache.env
    - redis.env
  notify: Restart netbox

- name: Update configuration files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ netbox_base_dir }}/{{ item }}"
    mode: "0644"
  loop:
    - docker-compose.yml
    - extra.py
  notify: Restart netbox

- name: Remove outdated files
  ansible.builtin.file:
    path: "{{ netbox_base_dir }}/{{ item }}"
    state: absent
  loop:
    - netbox.env
    - configuration/configuration.py
    - configuration/gunicorn_config.py

- name: Ensure services are running
  community.docker.docker_compose:
    project_src: "{{ netbox_base_dir }}"
    state: present
